# News

Analysis of the two datasets about how long it takes for news to reach the m

```{r}
suppressPackageStartupMessages({
  library("ggplot2")
  library("dplyr")
})

PROJ <- Project()
battle_news_wgts_1 <- PROJ$db[["battle_news_wgts_1"]]
battle_news_wgts_2 <- PROJ$db[["battle_news_wgts_2"]]
battles <- PROJ$db[["battles"]]
```

## News 1

The first news dataset uses when the end of the battle (or days of the battle) are first reported.

```{r}
news1 <- 
  (merge(select(filter(battles, significance == "A"),
              battle, battle_name_short, end_date, start_date, theater),
       battle_news_wgts_1)
 %>% mutate(lag = as.integer(date - end_date))
 )
```

```{r}
(ggplot(news1, aes(y = battle_name_short, x = lag, size = wgt)) 
  + geom_point()
  + facet_grid(theater ~ ., scales = "free", space = "free")
 )

```

Summary of Lag data

```{r}
news1_mean <- group_by(news1, battle, theater) %>% summarise(lag = sum(wgt * lag))
summary(news1_mean)

```

Summary of Lag data by theater
```{r}
group_by(tbl_df(news1_mean), theater) %>% summarise(mean = mean(lag), median = median(lag), min = min(lag), max = max(lag))

```

## News 2

The second news data set, which uses all news paper articles about the battle.

```{r}
news2 <- 
  (merge(select(filter(battles, significance == "A"),
              battle, battle_name_short, end_date, start_date, theater),
       battle_news_wgts_2)
 %>% mutate(lag = as.integer(date - end_date))
 )
```

```{r}
(ggplot(news2, aes(y = battle_name_short, x = lag, size = wgt2)) 
  + geom_point()
  + facet_grid(theater ~ ., scales = "free", space = "free")
 )

```

Summary of Lag data

```{r}
news2_mean <- group_by(news2, battle, theater) %>% summarise(lag = sum(wgt2 * lag))
summary(news2_mean)

```

Summary of Lag data by theater
```{r}
group_by(tbl_df(news2_mean), theater) %>% summarise(mean = mean(lag), median = median(lag), min = min(lag), max = max(lag))

```
  
